# Generated by Django 4.0.1 on 2022-01-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_delete_tutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='subcatgeory',
            new_name='subcategory',
        ),
    ]
